---
title: "An hybrid approach for the analysis of complex categorical data structures"
author: "supplementary material"
date: "2/15/2022"
output: html_document
---

#### Setup

```{r setup, message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("clustrd")
library("ggrepel")
library("kableExtra")
library("purrr")
library("patchwork")
```



#### Load the pre-processed dataset and display the first few lines.

```{r meta_item_build}
load("distance_learning_data.RData")
distance_learning_data %>% slice(1:10) %>% 
  knitr::kable() %>% 
  kable_styling(bootstrap_options = "striped", font_size = 8)
```

#### Cluster CA meta-item build

```{r CCAsol, warning=FALSE,message=FALSE,results='hide',cache=TRUE}
set.seed(1234)
CCA_solution = clusmca(distance_learning_data, nclus = 4, nstart=200)
```

- Re-label the meta-item solution to ease interpretation
```{r re_label, warning=FALSE,message=FALSE,cache=TRUE}
DL_responses = tibble(dl_perception = CCA_solution$cluster) %>% 
  mutate(across(everything(), as.factor),
          dl_perception = fct_recode(dl_perception,
                            `1` = "2",
                            `2` = "1",
                            `3` = "3",
                            `4` = "4"),
          dl_perception = parse_double(as.character(dl_perception))
         )

CCA_solution$cluster=DL_responses$dl_perception
```

- Create ggplot objects  
```{r create_plots, warning=FALSE,message=FALSE,fig.show='hide',cache=TRUE}
DL_solution_plot = plot(CCA_solution,what = c(F,T),
                      cludesc = T,
                      subplot = T,
                      save.only = T)
```

- Recreate Figure 2 from the paper: attributes map, with  labels (rough) adjustment

```{r, warning=FALSE,message=FALSE}
DL_solution_plot$map$data %>% 
  mutate(d1=-1*d1,
    attnam_short=str_replace(attnam, pattern="\\.agree",replacement="_ag"),
    attnam_short=str_replace(attnam_short, pattern="_agree",replacement="_ag"),
    attnam_short=str_replace(attnam_short, pattern=".strongly",replacement="_str_"),
    attnam_short=str_replace(attnam_short, pattern="_disagree",replacement="_dis"),
    attnam_short=str_replace(attnam_short, pattern="\\.disagree",replacement="_dis"),
    attnam_short=str_replace(attnam_short, pattern="\\.dont_know",replacement="_do_kn"),
    attnam_short=str_replace(attnam_short, pattern="__",replacement="_"),
    agreement=str_remove(attnam_short,"Q\\d{2}_"),
    agreement=str_replace(agreement,"^str_dis$","a: strongly disagree"),
    agreement=str_replace(agreement,"^dis$","b: disagree"),
    agreement=str_replace(agreement,"^ag$","c: agree"),
    agreement=str_replace(agreement,"^str_ag$","d: strongly agree"),
    agreement=str_replace(agreement,"^do_kn$","e: don't know")
    ) %>% 
  filter(!str_detect(attnam_short,"_do_kn")) %>% 
    ggplot(aes(x=d1,y=d2, label=attnam_short, colour=agreement))  +
    geom_text_repel(size=3,alpha=.75,max.overlaps = 20)+
    geom_vline(xintercept=0)+
    geom_hline(yintercept=0)+ 
    theme_bw()+xlab("")+ylab("")+
    theme(axis.text = element_blank())
```

- Recreate Figure 3 from the paper: cluster characterization  

```{r, warning=FALSE,message=FALSE,fig.height=8}
cluster_characterization_data = DL_solution_plot$stdres %>% map(.f=~.x$data %>% 
                                  filter(!str_detect(lbls,"dont_know")) %>% 
                                  slice(1:15) %>%  
                                  mutate(newplace=15:1))

C1_plot = cluster_characterization_data[[1]] %>% 
  ggplot() + 
  geom_segment(aes(x=0,xend=value,y=newplace,yend=newplace),
            linejoin = "round",lwd=2,alpha=.25,col="red") +
            geom_text(aes(x=value,y=newplace,label = lbls),size=2)+
            xlim(-8.5,8.5)+ggtitle(label = "C1: 25.3%")+
            theme_bw() + xlab("")+ylab("")

C2_plot =  cluster_characterization_data[[2]] %>% 
  ggplot() + geom_segment(aes(x=0,xend=value,y=newplace,yend=newplace),
                          linejoin = "round",lwd=2,alpha=.25,col="green") +
            geom_text(aes(x=value,y=newplace,label = lbls),size=2)+xlim(-8.5,8.5)+
  ggtitle(label = "C2: 41.1%") + xlab("")+ylab("")+theme_bw()

C3_plot =  cluster_characterization_data[[3]] %>% 
  ggplot() + geom_segment(aes(x=0,xend=value,y=newplace,yend=newplace),
                          linejoin = "round",lwd=2,alpha=.25,col="blue") +
            geom_text(aes(x=value,y=newplace,label = lbls),size=2)+xlim(-8.5,8.5)+
  ggtitle(label = "C3: 24.9%") + xlab("")+ylab("")+theme_bw()

C4_plot =  cluster_characterization_data[[4]] %>% 
  ggplot() + geom_segment(aes(x=0,xend=value,y=newplace,yend=newplace),
                          linejoin = "round",lwd=2,alpha=.25,col="magenta") +
            geom_text(aes(x=value,y=newplace,label = lbls),size=2)+xlim(-8.5,8.5)+
  ggtitle(label = "C4: 8.7%") + xlab("")+ylab("")+theme_bw()


(C1_plot | C2_plot)  /
(C3_plot | C4_plot)
```
